image: node:8

cache:
  paths:
  - node_modules/

test:
  stage: test
  script:
    - yarn install
    - yarn test:ci

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build --out-dir ./public --public-url ./
  artifacts:
    paths:
    - public
  only:
  - master
