image: node:8

cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build --out-dir ./public --public-url ./luxord
  artifacts:
    paths:
    - public
  only:
  - master
