image: node:8

cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - cp -r dist public
  artifacts:
    paths:
    - public
  only:
  - master
